Repository akheron/typera-openapi, pull requests merged in 2021-01, with the labels that each got.

#23 Configure release-drafter categories
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-labeler.yml
Labels: chore

#21 Support route tags
  README.md
  src/generate.ts
  tests/__snapshots__/generate.spec.ts.snap
  tests/test-routes.ts
Labels: feature

#25 Allow custom route function
  src/generate.ts
  tests/__snapshots__/generate.spec.ts.snap
  tests/test-routes.ts
Labels: fix

#26 Support the Date type
  README.md
  src/generate.ts
  src/utils.ts
  tests/__snapshots__/generate.spec.ts.snap
  tests/test-routes.ts
Labels: feature

#27 Support setting descriptions for object properties
  README.md
  src/generate.ts
  tests/__snapshots__/generate.spec.ts.snap
  tests/test-routes.ts
Labels: feature
